### PR TITLE
WIP: support meshes when loading URDF

### PR DESCRIPTION
**Pull request by rdeits**

### CODE REVIEW

**Comment by rdeits** [comment]
@tkoolen can you take a look at this? I think there may be an issue with the way we're parsing Valkyrie's kinematics 😉 

screen shot 2016-05-27 at 1 54 30 pm

Note that I'm currently not handling `package://` when loading mesh files, so I've just hard-coded my drake install path inside `parse_urdf.jl`. You'll have to change that to get it to run on your machine.

**Comment by rdeits** [comment]
Actually, it might be a bug on my end. Using the generated geometry instead of the meshes gives the right kinematic structure: 

screen shot 2016-05-27 at 2 12 54 pm

**Comment by rdeits** [comment]
Ah, I see. The problem is that `RigidBodyTreeInspector.parse_urdf` returns the links in the order in which they're encountered in the URDF, not the toposorted order of the mechanism. Maybe we really do need a `mechanism` argument to `parse_urdf`?

**Comment by tkoolen** [comment]
doh. Yeah I guess so.

**Comment by rdeits** [comment]
Done! 
screen shot 2016-05-27 at 3 25 19 pm

**Comment by tkoolen** [comment]
Cool!

**Comment by rdeits** [comment]
Okay, it's working! This is great. It takes about 0.3 to 0.4 seconds to construct the visualizer with meshes for Val. That's because I'm actually reading in the entire mesh file with MeshIO and then re-packaging it into the LCM message. But that only happens when you construct the visualizer, not every time you draw, so interacting with the model is still super fast. 

If that 0.3 seconds is annoying, we could consider doing what Drake does by only storing the filename of the mesh, not its data. I could even imagine having a `LazyMesh` type that exists only as a filename unless you try to ask for its vertices or faces.

**Comment by rdeits** [comment]
Hm, I'm not sure I believe these inertias:

screen shot 2016-05-27 at 3 44 48 pm

**Comment by rdeits** [comment]
Inertias for Atlas look _much_ saner: 

screen shot 2016-05-27 at 4 31 01 pm

**Comment by tkoolen** [comment]
That's strange, because the inertias look OK in SCS (except for the beetlejuice nose):

image

image

**Comment by tkoolen** [comment]
This is with their [models/val_description/sdf/valkyrie_sim.sdf](https://bitbucket.org/ihmcrobotics/ihmc-open-robotics-software/src/575d33e1ab064f4e5957096414376fc011a98bce/Valkyrie/resources/models/val_description/sdf/valkyrie_sim.sdf?at=develop&fileviewer=file-view-default).

**Comment by tkoolen** [comment]
The model they use with on the real robot looks even more plausible:
image

**Comment by tkoolen** [comment]
I think also on Atlas, some ellipsoids look strangely rotated.

**Comment by rdeits** [comment]
Yes, agreed. I must be doing something wrong with the transforms. 

I believe the huge spheres on my version of the model are occurring because I take the actual link mass into account when constructing the ellipsoid. Drake assumes a fixed density (the density of wood) for constructing the ellipsoids for all bodies, but I try to create an ellipsoid with the correct inertias _and_ total mass, assuming a constant density for each link. A link with a very small mass but relatively large inertia will show up as a huge sphere in my version, and a small sphere in the Drake version. I actually think what I'm doing is more correct (although I may also have bugs): if a link really does have a huge inertia and tiny mass, then it's likely just an error in the URDF.

**Comment by tkoolen** [comment]
See [here](https://bitbucket.org/ihmcrobotics/ihmc-open-robotics-software/src/575d33e1ab064f4e5957096414376fc011a98bce/CommonWalkingControlModules/src/us/ihmc/commonWalkingControlModules/visualizer/CommonInertiaEllipsoidsVisualizer.java?at=develop&fileviewer=file-view-default) for how IHMC computes the inertia ellipsoids (method createEllipsoid at the end of the file).

**Comment by rdeits** [comment]
Ok, cool. I'm doing the same calculation (although less efficiently...I'll fix that). The huge spheres correspond to some of the links in the head which have mass 1e-5 and inertias of 1e-6, which corresponds to a sphere of radius 0.25 meters.

**Comment by rdeits** [comment]
Ok, filtering out all links with mass less than 1 gram, I get: 

screen shot 2016-05-27 at 5 34 54 pm

And here it is again, with Drake's inertial ellipsoids overlaid:

screen shot 2016-05-27 at 5 35 19 pm

**Comment by rdeits** [comment]
Atlas also looks more reasonable now:

screen shot 2016-05-27 at 5 37 30 pm

**Comment by rdeits** [comment]
Ok, good enough for now :). I'll figure out how to get around the `package://` thing later.

**Comment by tkoolen** [comment]
Awesome. That's cool that you can just overlay the drake ellipsoids.

**Comment by tkoolen** [comment]
Out of interest, do you know the origin of the Valkyrie URDF? Is it converted from one of the IHMC SDFs? If so which one?

**Comment by rdeits** [comment]
No, I have no idea. Perhaps we added those extra inertias ourselves to avoid having links with no inertia?

**Pull request merged**
