### PR TITLE
Improve support for mechanisms with loops.

### LINKED ISSUE #21: Better support for Mechanisms with loops
Loop joints are currently not handled in the generation of geometry for a `Mechanism`. 

Here are two proposed ways to improve this situation:

Let `f(body, joint)` be the frame associated with a joint (either frame before or frame after) that is rigidly fixed to the body.

First version:
```
for each body
    for each joint attached to body
        create a cylinder between the origin of f(body, joint) and the body's default frame
    end
end
```

```
for each body
    for each pair (j1, j2) of joints attached to body, with j1 != j2
        create a cylinder between the origins of f(body, j1) and f(body, j2)
    end
end
```

@rdeits, which one do you prefer? I kind of like the second better.

### PR DESCRIPTION
**Pull request by tkoolen**
Draw cylinders between all joint frames fixed to a body.

Draw spheres at frames before all joints (not only tree joints).

Fixes #21.

### CODE REVIEW

**Comment by tkoolen** [comment]
Don't merge yet; fixing another bug.

**Comment by tkoolen** [comment]
OK, should be fixed.

**Comment by tkoolen** [comment]
CC: @Symplectomorphism
screenshot-2017-06-07_17 07 34

**Comment by rdeits** [comment]
awesome, thanks!

**Pull request merged**
