### PR TITLE
ODE callback

### PR DESCRIPTION
**Pull request by tkoolen**
Adds `DrakeVisualizerSink`, which is a callback for `MuntheKaasIntegrator` that allows you to visualize the mechanism while it is simulating.

(also adds ipynb_checkpoitns to gitignore)

Needs tests before merge; just so you're aware that this exists.

### CODE REVIEW

**Comment by rdeits** [comment]
I'm thinking about tagging a new patch release to get the compatibility fixes with RBD 0.1.0. Do you want this included before I make the release?

**Comment by tkoolen** [comment]
Not necessarily. I don't think I have time to write tests for it today, so just go ahead and tag without this PR.

**Comment by rdeits** [comment]
ok, no problem

**Comment by rdeits** [comment]
Any updates on this? Is it something we want for juliacon?

**Comment by tkoolen** [comment]
Yeah, would be nice to have it. I still need to add some tests. I'm going to focus on visualizing closed-loop mechanisms first.

**Comment by rdeits** [comment]
this is great, thanks!

**Pull request merged**
