### PR TITLE
use MechanismGeometries.jl

### PR DESCRIPTION
**Pull request by rdeits**
cc @tkoolen 

~~(currently requires MechanismGeometries.jl and DrakeVisualizer.jl at master)~~

### CODE REVIEW

**Comment by rdeits** [comment]
@tkoolen could you try this branch out with your sim code? I *think* I properly made it backwards-compatible but I may have missed some deprecations.

**Comment by tkoolen** [comment]
In RigidBodySim, the following doesn't work anymore:

```julia
vis = Visualizer(mechanism, RigidBodyTreeInspector.parse_urdf(urdf, mechanism))
```

after the depwarn for `parse_urdf`, I get

```julia
MethodError: Cannot `convert` an object of type MechanismGeometries.VisualElement{GeometryTypes.HyperRectangle{3,Float32},CoordinateTransformations.AffineMap{Rotations.RotMatrix{3,Float64,9},StaticArrays.SArray{Tuple{3},Float64,1,3}}} to an object of type Symbol
This may have arisen from a call to the constructor Symbol(...),
since type constructors fall back to convert methods.

Stacktrace:
 [1] copy!(::IndexLinear, ::Array{Symbol,1}, ::IndexLinear, ::Array{Any,1}) at ./abstractarray.jl:656
 [2] getindex(::DrakeVisualizer.Visualizer, ::Array{MechanismGeometries.VisualElement,1}) at /Users/twan/code/julia/RigidBodyDynamics/v0.6/DrakeVisualizer/src/visualizer.jl:184
 [3] #Visualizer#19(::Bool, ::Bool, ::Type{T} where T, ::RigidBodyDynamics.Mechanism{Float64}, ::Array{MechanismGeometries.VisualElement,1}) at /Users/twan/code/julia/RigidBodyDynamics/v0.6/RigidBodyTreeInspector/src/visualizer.jl:114
 [4] DrakeVisualizer.Visualizer(::RigidBodyDynamics.Mechanism{Float64}, ::Array{MechanismGeometries.VisualElement,1}) at /Users/twan/code/julia/RigidBodyDynamics/v0.6/RigidBodyTreeInspector/src/visualizer.jl:113
 [5] include_string(::String, ::String) at ./loading.jl:522
```

This is from the RigidBodySim quick start guide.

**Comment by rdeits** [comment]
Ah, thanks. I afraid the interfaces here suffer a lot from the fact that I didn't really understand type piracy when I wrote them...

**Comment by rdeits** [comment]
Ok, should be fixed.

**Comment by tkoolen** [comment]
Confirmed, thank you!

**Comment by rdeits** [comment]
Ok, dependency versions are all tagged, so I'll merge this once CI finishes.

**Pull request merged**
